import type { Metadata } from "next";
import { Exo, Geist, Geist_Mono ,Noto_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import WrapperForAuthProvider from "./_components/WrapperForAuthProvider/WrapperForAuthProvider";
import { getCart } from "@/ApiServices/cart.servicies";
import CartDataProvider from "./_context/CartDataProvider";
import { WishlistDataProvider } from "./_context/WishlistDataProvider";
 const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});
const exo = Exo({
  variable: "--font-sans-serif-Exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  
  
  const res = await getCart()
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${exo.className} antialiased`}>
       <CartDataProvider res={res}  >
       <WrapperForAuthProvider>
        <WishlistDataProvider>
       <Navbar />
        <div className="min-h-screen bg-gray-100">
        {children}
        </div>
        <Toaster/>
        <Footer/>
        </WishlistDataProvider>
       </WrapperForAuthProvider>
       </CartDataProvider>
      </body>
    </html>
  );
}
